### ISSUE TITLE
Not Uninstalling Fully - Framebuffer service auto-reenables on OPKG upgrade

### ISSUE THREAD

**Issue by Servinjesus1** [ddvk/remarkable2-framebuffer#100]
I cannot update my packages because rm2fb re-enables its service even when the client package itself is uninstalled. My /etc/version of xochitl is `20220530145832`, which doesn't seem supported by rm2fb yet, and 2.14.0.824 is apparently the latest version I can get. I am trying to upgrade things, including xochitl, but cannot because every time I run `opkg upgrade` it begins configuring the display and the rm2fb service blocks any progress. I have tried uninstalling rm2fb (`opkg remove rm2fb-client` and all dependents as necessary), and purging my services of the framebuffer (`systemctl disable rm2fb`), but something keeps re-making the symlink.

**Comment by Servinjesus1** [comment]
Removing `display` worked. Not sure why I can't get `2.14.0.861` yet, but I will post my hashes to #18.

**Comment by Eeems** [comment]
This Repo is for the rm2fb code, not the toltec package. That said, rm2fb-client is not the rm2fb server, that is contained in the display package.
