### ISSUE TITLE
rm 2fb.service: Failed with result 'exit-code'

### ISSUE THREAD

**Issue by PDF2468** [ddvk/remarkable2-framebuffer#109]
I installed rm2fd through collect, but was always prompted
Job for rm2fb. service failed because the control process exited with error code.
See "systemctl status rm2fb.service" and "journalctl -xe" for details.

I checked the log and found that the problem was "Missing address for function 'getInstance'"

The version of my device is str 2.14.3.1005. I checked that it is supported.
I want to know how to solve it, please advise!
I looked at issues # 18 but didn't get an answer

**Comment by Eeems** [comment]
#18 is the correct place to ask about this, not opening a new issue.
