### ISSUE TITLE
Screen sharing not working after install remarkable2-framebuffer

### ISSUE THREAD

**Issue by ignaciolg** [ddvk/remarkable2-framebuffer#117]
Hi, 

I've installed a couple of packages, including the remarkable2-framebuffer. 

After installing it, I realised that the screen sharing was not working. 

I can connect to the desktop app, and I can see the red dot if I hover the tablet with the pen, but the drawn image is no longer synced from the device to the desktop app.

I'm on the latest version 2.15.1.1189

Thx in advance

**Comment by ddvk** [comment]
hm, the last version should have worked

**Comment by ignaciolg** [comment]
My fault, I'm using Toltec and they are still on the 0.0.27 version. 

I will try the 0.0.29 and install it manually. 

Sorry for opening the ticket before realising where the problem was.
