### ISSUE TITLE
launcher support for rm2fb

### ISSUE THREAD

**Issue by raisjn** [ddvk/remarkable2-framebuffer#15]
This task is to add the ability for launchers to use the LD_PRELOAD shim when launching applications.

Launchers:

* draft: single task launcher
* oxide: multi task launcher
* remux: multi task launcher

The main issue with rm2fb and launchers is interacting with xochitl, since xochitl will spawn its own SWTCON thread. 

Note that launchers will have to use rm2fb LD_PRELOAD shim to display to screen

**Comment by raisjn** [comment]
i'd be fine with our first launcher being ddvk's remarkable-touchgestures + associated scripts to toggle between draft and xochitl

**Comment by ddvk** [comment]
this works almost out of the box, as the LD_PRELOAD gets passed to the child processes.

**Comment by Witos** [comment]
@raisjn , did you manage to launch oxide on rm2?

**Comment by raisjn** [comment]
Yes, I've run oxide on rM2, I don't recall if I got tarnish and everything else working, but I think I did at one point

**Comment by raisjn** [comment]
this is now done through the toltec package and systemd environment variables
