### ISSUE TITLE
investigate fast drawing

### ISSUE THREAD

**Issue by raisjn** [ddvk/remarkable2-framebuffer#19]
things to look into:

* is it a parameter in sendUpdate
* is it a member on EPFramebuffer (or canvas)
* is it a setting used to dictate speed of vsync/flip thread (or type of flipping)
* ???

**Comment by ddvk** [comment]
SendUpdate has several overloads. When using `SendUpdate(QRect, WaveForm, UpdateFlags)` this is achieved with: waveform 1, flags: 4
