### ISSUE TITLE
koreader touch input doesn't work (stylus input is fine)

### ISSUE THREAD

**Issue by Witos** [ddvk/remarkable2-framebuffer#20]
After setting up koreader on remarkable2, I have a problem with a touch input. It doesn't work. Operating using stylus works without any problems, but the touching using fingers does not. Is it a issue of the current remarkable2-framebuffer set-up or the koreader itself?

**Comment by ddvk** [comment]
get the latest master of koreader

**Comment by raisjn** [comment]
isn't the x axis also inverted? or is that fix in master?

**Comment by ddvk** [comment]
no, there are a couple of fixes that need to be added  (x y adjustment and the inverted x)

**Comment by Witos** [comment]
I built latest koreader master and tested. The problem remains. Maybe my set-up is wrong:
LD_PRELOAD=/home/root/fb/librm2fb_server.so /usr/bin/remarkable-shutdown &
LD_PRELOAD=/home/root/fb/librm2fb_client.so ./koreader.sh
?

**Comment by ddvk** [comment]
koreader  needs some minor changes,  i ll push them
when i have time

**Comment by ddvk** [comment]
@Witos 
here are the changes that needed for koreader:
(and the latest frontend/device/gesturerecognizer.lua)

https://github.com/ddvk/koreader/commit/31d1f7b25150b32a1de60514e365e71990219b2d

**Comment by Witos** [comment]
@ddvk , compiled your repo, there is a crash on start-up. Attaching crash.log
[crash.log](https://github.com/ddvk/remarkable2-framebuffer/files/5538277/crash.log)

**Comment by Witos** [comment]
I compiled the repo, patch didn't help with touch input, but maybe I do sth wrong...

**Comment by ddvk** [comment]
i added a minor fix, you can get the latest version, same repo. i am ashamed to admit, but i can't compile koreader at the moment.

**Comment by Witos** [comment]
Damn it, I missed that you didn't commit your patch on master but on rm2, will try again. Maybe I can help with compilation somehow? 

Generally, I'm interested in koreader / remarkable development,I know some stuff, I've been Linux embedded dev for few years..

**Comment by Witos** [comment]
#Good news: touch works, at least at basic level.
#Bad news: the screen is not refreshed properly. I had some minor issues in the previous koreader version but I fixed it turning "night mode" on and off. This time it doesn't help.I suspect it might be regression in koreader, I'll check vanilla version over the weekend. I'm using rm2-fb today checkout, and rm2 branch of koreader. ![image](https://user-images.githubusercontent.com/132660/99121599-f659d200-25fc-11eb-982a-f3dc5010e8f3.jpeg)

**Comment by Witos** [comment]
Good news: I rebooted the devices, set-up everything once again. It works like a charm. Will test it for the few days.

**Comment by ddvk** [comment]
you can try the latest: lib2rmfb_server, should have refresh etc

**Comment by Witos** [comment]
Thanks @ddvk , I think it's worth to make Pull Request to koreader with this patch.
It works fine so far for me. Now I need to make wifi in Koreader work...
