### ISSUE TITLE
demo.gif is a dead-end git-lfs pointer

### ISSUE THREAD

**Issue by burlapsax** [ddvk/remarkable2-framebuffer#22]
In [README.md](https://github.com/ddvk/remarkable2-framebuffer/blob/829546a877e0b1358caa09bb4aa07f7f6d18e53e/README.md#demo), there is a link to a [file in the repo's ./docs/ directory](https://github.com/ddvk/remarkable2-framebuffer/blob/829546a877e0b1358caa09bb4aa07f7f6d18e53e/docs/demo.gif), which looks as if it's supposed to be a 17.6 MB animated GIF, but turns out to be a 133-byte manifest file when cloning the repo locally or previewing it in github:

![image](https://user-images.githubusercontent.com/7128908/99141048-881d0b80-260c-11eb-9b4e-3da561eb9d67.png)

![image](https://user-images.githubusercontent.com/7128908/99141123-6ec88f00-260d-11eb-962e-63c3f757feb7.png)

![image](https://user-images.githubusercontent.com/7128908/99141129-80aa3200-260d-11eb-9c0a-406361dc4ec6.png)

As far as I can tell, this seems like an issue relating to Git LFS – perhaps due to missing dependencies in the system from which the file was originally committed/pushed. **[This discussion](https://github.com/git-lfs/git-lfs/issues/3128) may shed some light on cause and/or solution.**

**Comment by ddvk** [comment]
i ve used up my 1gb free lfs quota

**Comment by Eeems** [comment]
@ddvk host it on imgur instead?

**Comment by ddvk** [comment]
@Eeems I didn't really try it, but: https://stackoverflow.com/questions/37750270/unable-to-embed-a-gif-on-imgur-to-a-readme-md-on-github

**Comment by ddvk** [comment]
added just a link
