### ISSUE TITLE
refresh rate

### ISSUE THREAD

**Issue by pjebs** [ddvk/remarkable2-framebuffer#25]
If this project succeeds, can I use it as a second monitor with a decent refresh rate (like Dasung monitor)

**Comment by Eeems** [comment]
That isn't in the scope of this project. Another project would need to build what would be needed for a computer to use the rM as a monitor.

**Comment by pjebs** [comment]
Yes. There is another project that makes it into a vpn client. It is built for remarkable 1. They are awaiting for this project to succeed before they can move on to remarkable 2.

However, is this project capable of the kind of refresh rates for word processing, and basic internet browsing with a significant lag for mouse movements?

**Comment by Eeems** [comment]
I think it's less of a question of if this project is capable of the kind of refresh rates needed, and more of a question on if the screen itself can handle it. What kind of refresh rates were you considering to be decent?

**Comment by pjebs** [comment]
Not sure of a number. Just whether there is perceived lag with mouse movements: https://www.youtube.com/watch?v=5pevlmk5kQs

**Comment by ddvk** [comment]
well, if partial upate latency is similiar there should be no problem, you can just try vnc client

**Comment by pjebs** [comment]
What does partial update latency mean?

**Comment by ddvk** [comment]
@pjebs the rm has several types of screen updates. 

talk is cheap, here's a demo of the of this in action : https://www.reddit.com/r/RemarkableTablet/comments/k3t9ea/using_the_rm2_as_an_external_monitor_x11vncvnsee/

**Comment by pjebs** [comment]
Based on the video it seems totally unsuitable as a monitor, cf to Dasung

**Comment by unphased** [comment]
the problem seen there is clearly the full (not partial) refreshing happening, which if it could be eliminated (or reasonably attenuated...) it seems the rM2 screen there is at least within a factor of 2 for latency, which is decent.

**Comment by stolsvik** [comment]
@ddvk That's amazing! Must faster than I had thought!
