### ISSUE TITLE
[Question] Reading the framebuffer

### ISSUE THREAD

**Issue by lfourquaux** [ddvk/remarkable2-framebuffer#33]
Is there a way, on a remarkable 2, to read the framebuffer when xochitl is running (in order to stream it to another device)?

**Comment by Eeems** [comment]
There is a pull request on reStream that does just that: https://github.com/rien/reStream/pull/31

**Comment by raisjn** [comment]
there are two ways (in this repo):

* you can look at src/xofb for a standalone LD_PRELOAD shim (librm2fb_xofb) that will expose the framebuffer in /dev/shm
* if you use the rm2fb server, when you hook xochitl with LD_PRELOAD of librm2fb_client, it will also expose the framebuffer in /dev/shm/

i believe people have had success with xofb and restream (by updating a few variables in reStream)
