### ISSUE TITLE
[release] bump assets to 1.0.1

### ISSUE THREAD

**Issue by mehalter** [ddvk/remarkable2-framebuffer#51]
How can I tell which rm2fb version is on Toltec? It shows that it has version 1.0.0-7, and I'm just wondering when I can tell that this has been updated to the newest version v0.0.3. I'm looking forward to the new PR that it includes as well as just future reference as newer versions are released. Thank you!

**Comment by Eeems** [comment]
It was packaged before rm2fb had version numbers so it was created with 1.0.0

According to https://github.com/toltec-dev/toltec/blob/stable/package/rm2fb/package#L16 it's being pulled from cd2766864c7985fa50cdf85f4ae0a411d7ca4e56

**Comment by raisjn** [comment]
we will bump this repo's version to catch up to toltec's version (so we will probably turn v0.0.3 -> v1.0.1) and then we will stay aligned from there

**Comment by mehalter** [comment]
Ah ok, thanks so much! Very excited about this development, great work!

**Comment by mehalter** [comment]
Also I'm going to go ahead and close this as my question was resolved, hopefully others can find it if they have similar questions. Thanks again

**Comment by raisjn** [comment]
actually, this is more work than just bumping and matching toltec since there are files with the name '1.0.0' in the build. i am going to delete release v1.0.1 and look into it more later

**Comment by mehalter** [comment]
Was this resolved with #54 ? If so, could we tag a new release and update toltec?

**Comment by raisjn** [comment]
> Was this resolved with #54 ? If so, could we tag a new release and update toltec?

yes, will take care of it within a few days hopefully

**Comment by raisjn** [comment]
we are also dealing with the new xochitl 2.6 update, so maybe we will do both at same time. (expect it in next few days, still)

**Comment by raisjn** [comment]
this is new stable now
