### ISSUE TITLE
[toltec rm2fb 1.0.1-1] 2.6 Feedback

### ISSUE THREAD

**Issue by Pemo11235** [ddvk/remarkable2-framebuffer#56]
I just tried new rm2fb  toltec pack and this works greatly. GJ !

I just want to inform that the new pinch to zoom its kinda laggy and a bit inaccurate. The input itself is right but  the screen   doesn't show exactly where I am when in moving the 2 fingers during the gesture.
I hope that i express my self, is easier to watch lol

I guess is the limit of framebuffer server/client solution.

p.s. Thanks for the great work all of you do for community!

**Comment by raisjn** [comment]
thank you for reporting! i haven't upgraded to 2.6 yet, so i haven't seen all these cool features, but i think ddvk and matteo are on 2.6

it sounds like the waveforms are not well matched and they are using something faster than what we do? (or they use wait ioctl or other ioctls?)

**Comment by timower** [comment]
It's a problem with the server, I'm getting:
```
Unable to complete update: invalid waveform ( 6 )
Unable to complete update: invalid waveform ( 6 )
Unable to complete update: invalid waveform ( 6 )
....
```
when zooming and panning. I suspect the swtcon in xochitl was updated but not in remarkable-shutdown. Causing unknown waveform modes.

**Comment by raisjn** [comment]
that's very interesting and unfortunate. i was somewhat hoping the SWTCON is not changing (and us always having the shutdown binary if necessary), but now it looks like they can break SWTCON compat between versions :-( 

please let us know if it works when using xochitl as the host for rm2fb!

**Comment by ddvk** [comment]
they probably didnt update the shutdown binary

**Comment by timower** [comment]
Using xochitl as host for the server works. I was getting segfaults but it seems unrelated.

**Comment by mehalter** [comment]
I'm having some issues popping up after the update that I'm not sure if they should go here or in other places. I noticed that after the update `remux` stopped working which relies on `rm2fb`. When I start it manually with the command `remux` it shows a warning that I don't have rm2fb installed. I am also running into a weird issue with Koreader where the xochitl is bleeding through the UI and I get this weird frankenstein UI where touch events are going to both koreader and xochitl. I'm not sure if these issues should be opened with the respective packages or if this could be a result of something with `rm2fb`. Let me know what you think or if there's anything I could do to help identify the problem. Sorry in advanced if this comment is misplaced!

**Comment by mehalter** [comment]
Ignore the previous comment, I got it all fixed and working. rm2fb is working great on the new version!

**Comment by matteodelabre** [comment]
Since this is solved by running the server on `xochitl` instead of `remarkable-shutdown`, I’ll close this issue. The rm2fb package in Toltec was recently (toltec-dev/toltec#325) updated with this change, and should land in stable in the next merge.
