### ISSUE TITLE
rm2fb possibly not working on 2.8x

### ISSUE THREAD

**Issue by myfoxit** [ddvk/remarkable2-framebuffer#61]
rm2fb  installed via opgk does not work on 2.8 Beta. I opened therefore a issue here. So that we maybe can be ahead.

Journalctl only returns xochitl.service: Start request repeated too quickly. Trying to find out more and edit/update the thread

**Comment by Eeems** [comment]
Just a warning, but the EULA for the beta has stated in the past that you wont install third party software. You might want to review it to make sure you aren't in breach of that agreement.

**Comment by matteodelabre** [comment]
@myfoxit This should be fixed in release 0.0.5. That release just reached Toltec testing.
