### ISSUE TITLE
Waveform file with correct FPL_LOT and TFT_VID not found with latest toltek testing build

### ISSUE THREAD

**Issue by i-am-shodan** [ddvk/remarkable2-framebuffer#64]
I've just got a r2 and I am trying to set up koreader.

I installed the latest r2fb via toltek
`opkg install display`

Installed koreader from testing
`opkg install koreader`

Then I wrote a script to switch between xochitl and koreader (modelled on an old one). My plan was to get this working and then use genie to do the switch.

```
#!/bin/sh

# if koreader is running and we get swiped then we should
# kill koreader
if [ ! -z "`pidof koreader`"]; then
    echo "koreader is running, killing"
    killall koreader
    exit 0
fi

# otherwise stop the ui
systemctl stop xochitl

if [ ! -z "`pidof remarkable-shutdown`"]; then
    killall remarkable-shutdown
fi

LD_PRELOAD=/opt/lib/librm2fb_server.so.1.0.1 /usr/bin/remarkable-shutdown &
sleep 2

echo "Starting koreader"
LD_PRELOAD=/opt/lib/librm2fb_server.so.1.0.1
koreader

echo "Koreader has quit"

killall remarkable-shutdown
systemctl reset-failed xochitl
systemctl start xochitl
```

Script works pretty well but koreader has lots of graphical problems and isn't really usable. In stdout I see:
```
Error decoding barcode: EUFA8RBH9W3V00DSSAT -1.45!
Waveform file with correct FPL_LOT and TFT_VID not found, using fallback: /usr/share/remarkable/320_R299_AFC421_ED103TC2U2_VB3300-KCD_TC.wbf
Reading waveforms from /usr/share/remarkable/320_R299_AFC421_ED103TC2U2_VB3300-KCD_TC.wbf
```

And occasionally the following repeated.

`Pan failed: Invalid argument`

I'm assuming r2fb doesn't quite understand what waveforms it needs, picks one which then isn't that great.

**Comment by ddvk** [comment]
most likely 2 instances are running. the messages you come from the original binary that is driving the display which rm2fb piggybacks on
