### ISSUE TITLE
peer into xochitl memory and expose it as shared memory

### ISSUE THREAD

**Issue by raisjn** [ddvk/remarkable2-framebuffer#7]

**Comment by raisjnn** [comment]
https://github.com/ddvk/remarkable2-framebuffer/issues/5#issuecomment-718997763 has some interesting things to look at when trying to find this memory

another (less good) alternative is to hardcode the expected hash of each version of xochitl and the memory addresses we want to make shared.

**Comment by Eeems** [comment]
> [#5 (comment)](https://github.com/ddvk/remarkable2-framebuffer/issues/5#issuecomment-718997763) has some interesting things to look at when trying to find this memory
> 
> another (less good) alternative is to hardcode the expected hash of each version of xochitl and the memory addresses we want to make shared.

This would mean that there is more work required for every software release to get things working. Not an ideal solution but doable.

**Comment by raisjn** [comment]
I think there are a few avenues to investigate:

* using the stuff from reStream 
* intercepting malloc and using shared mem for framebuffer
* intercepting program main(), running initSWTCon() and smashing some pointers
* emitting dirty regions instead of having to screenshot whole buffer every time
* ???

**Comment by raisjn** [comment]
xofb.so does this, closing for now
