### ISSUE TITLE
Screensharing in 2.9 doesn't work 

### ISSUE THREAD

**Issue by ddvk** [ddvk/remarkable2-framebuffer#71]
First discussed here, https://github.com/ddvk/remarkable-hacks/issues/344
The updates don't seem to work with rm2fb_client even with the unmodified xochitl binary ...

**Comment by timower** [comment]
I saw this when looking in ghidra. We hook the update function of the xochitl app, which contains the logic to send the screen update to screensharing. 

The server xochitl does have an unhooked version of the update function but there the screen sharing function hasn't been started.

We should probably activate the screen sharing update signal in our hooked update function.

**Comment by ddvk** [comment]
which one is the rfb update?

**Comment by robfreundlich** [comment]
> We should probably activate the screen sharing update signal in our hooked update function.

Yes, please! There are many toltec packages that I'd like to use, but they all depend on this one. So it's a Hobson's Choice - screen sharing or the toltec packages.

**Comment by ddvk** [comment]
marking  as fixed
