### ISSUE TITLE
After installig rm2fb screen frozen

### ISSUE THREAD

**Issue by tabs3n** [ddvk/remarkable2-framebuffer#72]
Hello,

I just installed toltec after that everything is fine.
If i install rm2fb - client through toltec the screen gets frozen but i still have acces through ssh.
if i reboot the rm2 gets stucked in "loading".
if i remove rm2fb / toltec everything works again.
Is this a problem with the 2.10.0 Beta software version?

**Comment by ddvk** [comment]
the beta is not supported yet, iirc
