### ISSUE TITLE
unavailable for 2.10.1.332

### ISSUE THREAD

**Issue by NathanF98** [ddvk/remarkable2-framebuffer#77]
When I install rmfb2, the screen frozen. Is it not support 2.10.1.332 now?

**Comment by NathanF98** [comment]
I install with toltec. Does toltec use the latest version of rm2fb?

**Comment by Eeems** [comment]
> 
> 
> I install with toltec. Does toltec use the latest version of rm2fb?

No, it installs the latest available in the branch of toltec you are on. v0.0.8 isn't in stable yet, you'd have to switch to the testing branch: https://github.com/toltec-dev/toltec/blob/stable/docs/branches.md
