### ISSUE TITLE
Please remove 1.0.1 tag

### ISSUE THREAD

**Issue by Natureshadow** [ddvk/remarkable2-framebuffer#96]
Hi,

I am pulling in remarkable2-framebuffer in a build pipeline (packaging it for Debian), and stumbled upon a probably faulty tag `1.0.1`. It points to the same commit as `0.0.14`.

Could you please delete that tag?

Thanks,
Nik

**Comment by raisjn** [comment]
done, but what does package for debian mean?

**Comment by Natureshadow** [comment]
> what does package for debian mean?

That means that I am building `rm2fb-client` as a Debian package, to upload to official Debian repositories. And in practice, this means that I am working on making a vanilla Debian userland work from a chroot created using `debootstrap` inside the Codex Linux on the rM2.

Once it passes the NEW queue, you will find the package here: https://tracker.debian.org/teams/remarkable-pkg/

![image](https://user-images.githubusercontent.com/212972/169670854-12f74e46-ebac-4238-837f-06d6b0d681c3.png)
